_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
